# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20160326_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='video_choice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
