# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20160326_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='i_develop_strong_emotions_toward_people_i_can_rely_on',
            field=models.CharField(choices=[(-1, 'Refused'), (1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Somewhat disagree'), (4, 'Neither agree nor disagree'), (5, 'Somewhat agree'), (6, 'Agree'), (7, 'Strongly agree')], max_length=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='moral_standards_should_be_seen_as_individualistic_what_one_person_considers_to_be_moral_may_be_judged_as_immoral_by_another_person',
            field=models.CharField(choices=[(-1, 'Refused'), (1, 'Strongly agree'), (2, 'Agree'), (3, 'Somewhat agree'), (4, 'Neither agree nor disagree'), (5, 'Somewhat disagree'), (6, 'Disagree'), (7, 'Strongly disagree')], max_length=1),
        ),
        migrations.AlterField(
            model_name='survey',
            name='parents_should_empower_children_as_much_as_possible_so_that_they_may_follow_their_dreams',
            field=models.CharField(choices=[(-1, 'Refused'), (1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Somewhat disagree'), (4, 'Neither agree nor disagree'), (5, 'Somewhat agree'), (6, 'Agree'), (7, 'Strongly agree')], max_length=1),
        ),
    ]
